// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package schemapb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commonpb "github.com/milvus-io/milvus-proto/go-api/v2/commonpb"
	_ "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// @brief Field data type
type DataType int32

const (
	DataType_None           DataType = 0
	DataType_Bool           DataType = 1
	DataType_Int8           DataType = 2
	DataType_Int16          DataType = 3
	DataType_Int32          DataType = 4
	DataType_Int64          DataType = 5
	DataType_Float          DataType = 10
	DataType_Double         DataType = 11
	DataType_String         DataType = 20
	DataType_VarChar        DataType = 21
	DataType_Array          DataType = 22
	DataType_JSON           DataType = 23
	DataType_BinaryVector   DataType = 100
	DataType_FloatVector    DataType = 101
	DataType_Float16Vector  DataType = 102
	DataType_BFloat16Vector DataType = 103
)

var DataType_name = map[int32]string{
	0:   "None",
	1:   "Bool",
	2:   "Int8",
	3:   "Int16",
	4:   "Int32",
	5:   "Int64",
	10:  "Float",
	11:  "Double",
	20:  "String",
	21:  "VarChar",
	22:  "Array",
	23:  "JSON",
	100: "BinaryVector",
	101: "FloatVector",
	102: "Float16Vector",
	103: "BFloat16Vector",
}

var DataType_value = map[string]int32{
	"None":           0,
	"Bool":           1,
	"Int8":           2,
	"Int16":          3,
	"Int32":          4,
	"Int64":          5,
	"Float":          10,
	"Double":         11,
	"String":         20,
	"VarChar":        21,
	"Array":          22,
	"JSON":           23,
	"BinaryVector":   100,
	"FloatVector":    101,
	"Float16Vector":  102,
	"BFloat16Vector": 103,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

type FieldState int32

const (
	FieldState_FieldCreated  FieldState = 0
	FieldState_FieldCreating FieldState = 1
	FieldState_FieldDropping FieldState = 2
	FieldState_FieldDropped  FieldState = 3
)

var FieldState_name = map[int32]string{
	0: "FieldCreated",
	1: "FieldCreating",
	2: "FieldDropping",
	3: "FieldDropped",
}

var FieldState_value = map[string]int32{
	"FieldCreated":  0,
	"FieldCreating": 1,
	"FieldDropping": 2,
	"FieldDropped":  3,
}

func (x FieldState) String() string {
	return proto.EnumName(FieldState_name, int32(x))
}

func (FieldState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

//*
// @brief Field schema
type FieldSchema struct {
	FieldID      int64                    `protobuf:"varint,1,opt,name=fieldID,proto3" json:"fieldID,omitempty"`
	Name         string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsPrimaryKey bool                     `protobuf:"varint,3,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	Description  string                   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DataType     DataType                 `protobuf:"varint,5,opt,name=data_type,json=dataType,proto3,enum=milvus.proto.schema.DataType" json:"data_type,omitempty"`
	TypeParams   []*commonpb.KeyValuePair `protobuf:"bytes,6,rep,name=type_params,json=typeParams,proto3" json:"type_params,omitempty"`
	IndexParams  []*commonpb.KeyValuePair `protobuf:"bytes,7,rep,name=index_params,json=indexParams,proto3" json:"index_params,omitempty"`
	AutoID       bool                     `protobuf:"varint,8,opt,name=autoID,proto3" json:"autoID,omitempty"`
	State        FieldState               `protobuf:"varint,9,opt,name=state,proto3,enum=milvus.proto.schema.FieldState" json:"state,omitempty"`
	// state is `Created`.
	ElementType          DataType    `protobuf:"varint,10,opt,name=element_type,json=elementType,proto3,enum=milvus.proto.schema.DataType" json:"element_type,omitempty"`
	DefaultValue         *ValueField `protobuf:"bytes,11,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	IsDynamic            bool        `protobuf:"varint,12,opt,name=is_dynamic,json=isDynamic,proto3" json:"is_dynamic,omitempty"`
	IsPartitionKey       bool        `protobuf:"varint,13,opt,name=is_partition_key,json=isPartitionKey,proto3" json:"is_partition_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FieldSchema) Reset()         { *m = FieldSchema{} }
func (m *FieldSchema) String() string { return proto.CompactTextString(m) }
func (*FieldSchema) ProtoMessage()    {}
func (*FieldSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *FieldSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldSchema.Unmarshal(m, b)
}
func (m *FieldSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldSchema.Marshal(b, m, deterministic)
}
func (m *FieldSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldSchema.Merge(m, src)
}
func (m *FieldSchema) XXX_Size() int {
	return xxx_messageInfo_FieldSchema.Size(m)
}
func (m *FieldSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldSchema.DiscardUnknown(m)
}

var xxx_messageInfo_FieldSchema proto.InternalMessageInfo

func (m *FieldSchema) GetFieldID() int64 {
	if m != nil {
		return m.FieldID
	}
	return 0
}

func (m *FieldSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldSchema) GetIsPrimaryKey() bool {
	if m != nil {
		return m.IsPrimaryKey
	}
	return false
}

func (m *FieldSchema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FieldSchema) GetDataType() DataType {
	if m != nil {
		return m.DataType
	}
	return DataType_None
}

func (m *FieldSchema) GetTypeParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.TypeParams
	}
	return nil
}

func (m *FieldSchema) GetIndexParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.IndexParams
	}
	return nil
}

func (m *FieldSchema) GetAutoID() bool {
	if m != nil {
		return m.AutoID
	}
	return false
}

func (m *FieldSchema) GetState() FieldState {
	if m != nil {
		return m.State
	}
	return FieldState_FieldCreated
}

func (m *FieldSchema) GetElementType() DataType {
	if m != nil {
		return m.ElementType
	}
	return DataType_None
}

func (m *FieldSchema) GetDefaultValue() *ValueField {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *FieldSchema) GetIsDynamic() bool {
	if m != nil {
		return m.IsDynamic
	}
	return false
}

func (m *FieldSchema) GetIsPartitionKey() bool {
	if m != nil {
		return m.IsPartitionKey
	}
	return false
}

//*
// @brief Collection schema
type CollectionSchema struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AutoID               bool           `protobuf:"varint,3,opt,name=autoID,proto3" json:"autoID,omitempty"` // Deprecated: Do not use.
	Fields               []*FieldSchema `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	EnableDynamicField   bool           `protobuf:"varint,5,opt,name=enable_dynamic_field,json=enableDynamicField,proto3" json:"enable_dynamic_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CollectionSchema) Reset()         { *m = CollectionSchema{} }
func (m *CollectionSchema) String() string { return proto.CompactTextString(m) }
func (*CollectionSchema) ProtoMessage()    {}
func (*CollectionSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *CollectionSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionSchema.Unmarshal(m, b)
}
func (m *CollectionSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionSchema.Marshal(b, m, deterministic)
}
func (m *CollectionSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionSchema.Merge(m, src)
}
func (m *CollectionSchema) XXX_Size() int {
	return xxx_messageInfo_CollectionSchema.Size(m)
}
func (m *CollectionSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionSchema.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionSchema proto.InternalMessageInfo

func (m *CollectionSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CollectionSchema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// Deprecated: Do not use.
func (m *CollectionSchema) GetAutoID() bool {
	if m != nil {
		return m.AutoID
	}
	return false
}

func (m *CollectionSchema) GetFields() []*FieldSchema {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *CollectionSchema) GetEnableDynamicField() bool {
	if m != nil {
		return m.EnableDynamicField
	}
	return false
}

type BoolArray struct {
	Data                 []bool   `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolArray) Reset()         { *m = BoolArray{} }
func (m *BoolArray) String() string { return proto.CompactTextString(m) }
func (*BoolArray) ProtoMessage()    {}
func (*BoolArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *BoolArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolArray.Unmarshal(m, b)
}
func (m *BoolArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolArray.Marshal(b, m, deterministic)
}
func (m *BoolArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolArray.Merge(m, src)
}
func (m *BoolArray) XXX_Size() int {
	return xxx_messageInfo_BoolArray.Size(m)
}
func (m *BoolArray) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolArray.DiscardUnknown(m)
}

var xxx_messageInfo_BoolArray proto.InternalMessageInfo

func (m *BoolArray) GetData() []bool {
	if m != nil {
		return m.Data
	}
	return nil
}

type IntArray struct {
	Data                 []int32  `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntArray) Reset()         { *m = IntArray{} }
func (m *IntArray) String() string { return proto.CompactTextString(m) }
func (*IntArray) ProtoMessage()    {}
func (*IntArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *IntArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntArray.Unmarshal(m, b)
}
func (m *IntArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntArray.Marshal(b, m, deterministic)
}
func (m *IntArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntArray.Merge(m, src)
}
func (m *IntArray) XXX_Size() int {
	return xxx_messageInfo_IntArray.Size(m)
}
func (m *IntArray) XXX_DiscardUnknown() {
	xxx_messageInfo_IntArray.DiscardUnknown(m)
}

var xxx_messageInfo_IntArray proto.InternalMessageInfo

func (m *IntArray) GetData() []int32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type LongArray struct {
	Data                 []int64  `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongArray) Reset()         { *m = LongArray{} }
func (m *LongArray) String() string { return proto.CompactTextString(m) }
func (*LongArray) ProtoMessage()    {}
func (*LongArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *LongArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongArray.Unmarshal(m, b)
}
func (m *LongArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongArray.Marshal(b, m, deterministic)
}
func (m *LongArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongArray.Merge(m, src)
}
func (m *LongArray) XXX_Size() int {
	return xxx_messageInfo_LongArray.Size(m)
}
func (m *LongArray) XXX_DiscardUnknown() {
	xxx_messageInfo_LongArray.DiscardUnknown(m)
}

var xxx_messageInfo_LongArray proto.InternalMessageInfo

func (m *LongArray) GetData() []int64 {
	if m != nil {
		return m.Data
	}
	return nil
}

type FloatArray struct {
	Data                 []float32 `protobuf:"fixed32,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FloatArray) Reset()         { *m = FloatArray{} }
func (m *FloatArray) String() string { return proto.CompactTextString(m) }
func (*FloatArray) ProtoMessage()    {}
func (*FloatArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}

func (m *FloatArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatArray.Unmarshal(m, b)
}
func (m *FloatArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatArray.Marshal(b, m, deterministic)
}
func (m *FloatArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatArray.Merge(m, src)
}
func (m *FloatArray) XXX_Size() int {
	return xxx_messageInfo_FloatArray.Size(m)
}
func (m *FloatArray) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatArray.DiscardUnknown(m)
}

var xxx_messageInfo_FloatArray proto.InternalMessageInfo

func (m *FloatArray) GetData() []float32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type DoubleArray struct {
	Data                 []float64 `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DoubleArray) Reset()         { *m = DoubleArray{} }
func (m *DoubleArray) String() string { return proto.CompactTextString(m) }
func (*DoubleArray) ProtoMessage()    {}
func (*DoubleArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6}
}

func (m *DoubleArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleArray.Unmarshal(m, b)
}
func (m *DoubleArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleArray.Marshal(b, m, deterministic)
}
func (m *DoubleArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleArray.Merge(m, src)
}
func (m *DoubleArray) XXX_Size() int {
	return xxx_messageInfo_DoubleArray.Size(m)
}
func (m *DoubleArray) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleArray.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleArray proto.InternalMessageInfo

func (m *DoubleArray) GetData() []float64 {
	if m != nil {
		return m.Data
	}
	return nil
}

// For special fields such as bigdecimal, array...
type BytesArray struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BytesArray) Reset()         { *m = BytesArray{} }
func (m *BytesArray) String() string { return proto.CompactTextString(m) }
func (*BytesArray) ProtoMessage()    {}
func (*BytesArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{7}
}

func (m *BytesArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BytesArray.Unmarshal(m, b)
}
func (m *BytesArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BytesArray.Marshal(b, m, deterministic)
}
func (m *BytesArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BytesArray.Merge(m, src)
}
func (m *BytesArray) XXX_Size() int {
	return xxx_messageInfo_BytesArray.Size(m)
}
func (m *BytesArray) XXX_DiscardUnknown() {
	xxx_messageInfo_BytesArray.DiscardUnknown(m)
}

var xxx_messageInfo_BytesArray proto.InternalMessageInfo

func (m *BytesArray) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type StringArray struct {
	Data                 []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringArray) Reset()         { *m = StringArray{} }
func (m *StringArray) String() string { return proto.CompactTextString(m) }
func (*StringArray) ProtoMessage()    {}
func (*StringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8}
}

func (m *StringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArray.Unmarshal(m, b)
}
func (m *StringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArray.Marshal(b, m, deterministic)
}
func (m *StringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArray.Merge(m, src)
}
func (m *StringArray) XXX_Size() int {
	return xxx_messageInfo_StringArray.Size(m)
}
func (m *StringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArray.DiscardUnknown(m)
}

var xxx_messageInfo_StringArray proto.InternalMessageInfo

func (m *StringArray) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type ArrayArray struct {
	Data                 []*ScalarField `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	ElementType          DataType       `protobuf:"varint,2,opt,name=element_type,json=elementType,proto3,enum=milvus.proto.schema.DataType" json:"element_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ArrayArray) Reset()         { *m = ArrayArray{} }
func (m *ArrayArray) String() string { return proto.CompactTextString(m) }
func (*ArrayArray) ProtoMessage()    {}
func (*ArrayArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9}
}

func (m *ArrayArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayArray.Unmarshal(m, b)
}
func (m *ArrayArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayArray.Marshal(b, m, deterministic)
}
func (m *ArrayArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayArray.Merge(m, src)
}
func (m *ArrayArray) XXX_Size() int {
	return xxx_messageInfo_ArrayArray.Size(m)
}
func (m *ArrayArray) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayArray.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayArray proto.InternalMessageInfo

func (m *ArrayArray) GetData() []*ScalarField {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ArrayArray) GetElementType() DataType {
	if m != nil {
		return m.ElementType
	}
	return DataType_None
}

type JSONArray struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JSONArray) Reset()         { *m = JSONArray{} }
func (m *JSONArray) String() string { return proto.CompactTextString(m) }
func (*JSONArray) ProtoMessage()    {}
func (*JSONArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{10}
}

func (m *JSONArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JSONArray.Unmarshal(m, b)
}
func (m *JSONArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JSONArray.Marshal(b, m, deterministic)
}
func (m *JSONArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JSONArray.Merge(m, src)
}
func (m *JSONArray) XXX_Size() int {
	return xxx_messageInfo_JSONArray.Size(m)
}
func (m *JSONArray) XXX_DiscardUnknown() {
	xxx_messageInfo_JSONArray.DiscardUnknown(m)
}

var xxx_messageInfo_JSONArray proto.InternalMessageInfo

func (m *JSONArray) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ValueField struct {
	// Types that are valid to be assigned to Data:
	//	*ValueField_BoolData
	//	*ValueField_IntData
	//	*ValueField_LongData
	//	*ValueField_FloatData
	//	*ValueField_DoubleData
	//	*ValueField_StringData
	//	*ValueField_BytesData
	Data                 isValueField_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ValueField) Reset()         { *m = ValueField{} }
func (m *ValueField) String() string { return proto.CompactTextString(m) }
func (*ValueField) ProtoMessage()    {}
func (*ValueField) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{11}
}

func (m *ValueField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueField.Unmarshal(m, b)
}
func (m *ValueField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueField.Marshal(b, m, deterministic)
}
func (m *ValueField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueField.Merge(m, src)
}
func (m *ValueField) XXX_Size() int {
	return xxx_messageInfo_ValueField.Size(m)
}
func (m *ValueField) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueField.DiscardUnknown(m)
}

var xxx_messageInfo_ValueField proto.InternalMessageInfo

type isValueField_Data interface {
	isValueField_Data()
}

type ValueField_BoolData struct {
	BoolData bool `protobuf:"varint,1,opt,name=bool_data,json=boolData,proto3,oneof"`
}

type ValueField_IntData struct {
	IntData int32 `protobuf:"varint,2,opt,name=int_data,json=intData,proto3,oneof"`
}

type ValueField_LongData struct {
	LongData int64 `protobuf:"varint,3,opt,name=long_data,json=longData,proto3,oneof"`
}

type ValueField_FloatData struct {
	FloatData float32 `protobuf:"fixed32,4,opt,name=float_data,json=floatData,proto3,oneof"`
}

type ValueField_DoubleData struct {
	DoubleData float64 `protobuf:"fixed64,5,opt,name=double_data,json=doubleData,proto3,oneof"`
}

type ValueField_StringData struct {
	StringData string `protobuf:"bytes,6,opt,name=string_data,json=stringData,proto3,oneof"`
}

type ValueField_BytesData struct {
	BytesData []byte `protobuf:"bytes,7,opt,name=bytes_data,json=bytesData,proto3,oneof"`
}

func (*ValueField_BoolData) isValueField_Data() {}

func (*ValueField_IntData) isValueField_Data() {}

func (*ValueField_LongData) isValueField_Data() {}

func (*ValueField_FloatData) isValueField_Data() {}

func (*ValueField_DoubleData) isValueField_Data() {}

func (*ValueField_StringData) isValueField_Data() {}

func (*ValueField_BytesData) isValueField_Data() {}

func (m *ValueField) GetData() isValueField_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ValueField) GetBoolData() bool {
	if x, ok := m.GetData().(*ValueField_BoolData); ok {
		return x.BoolData
	}
	return false
}

func (m *ValueField) GetIntData() int32 {
	if x, ok := m.GetData().(*ValueField_IntData); ok {
		return x.IntData
	}
	return 0
}

func (m *ValueField) GetLongData() int64 {
	if x, ok := m.GetData().(*ValueField_LongData); ok {
		return x.LongData
	}
	return 0
}

func (m *ValueField) GetFloatData() float32 {
	if x, ok := m.GetData().(*ValueField_FloatData); ok {
		return x.FloatData
	}
	return 0
}

func (m *ValueField) GetDoubleData() float64 {
	if x, ok := m.GetData().(*ValueField_DoubleData); ok {
		return x.DoubleData
	}
	return 0
}

func (m *ValueField) GetStringData() string {
	if x, ok := m.GetData().(*ValueField_StringData); ok {
		return x.StringData
	}
	return ""
}

func (m *ValueField) GetBytesData() []byte {
	if x, ok := m.GetData().(*ValueField_BytesData); ok {
		return x.BytesData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ValueField) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ValueField_BoolData)(nil),
		(*ValueField_IntData)(nil),
		(*ValueField_LongData)(nil),
		(*ValueField_FloatData)(nil),
		(*ValueField_DoubleData)(nil),
		(*ValueField_StringData)(nil),
		(*ValueField_BytesData)(nil),
	}
}

type ScalarField struct {
	// Types that are valid to be assigned to Data:
	//	*ScalarField_BoolData
	//	*ScalarField_IntData
	//	*ScalarField_LongData
	//	*ScalarField_FloatData
	//	*ScalarField_DoubleData
	//	*ScalarField_StringData
	//	*ScalarField_BytesData
	//	*ScalarField_ArrayData
	//	*ScalarField_JsonData
	Data                 isScalarField_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ScalarField) Reset()         { *m = ScalarField{} }
func (m *ScalarField) String() string { return proto.CompactTextString(m) }
func (*ScalarField) ProtoMessage()    {}
func (*ScalarField) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{12}
}

func (m *ScalarField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarField.Unmarshal(m, b)
}
func (m *ScalarField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarField.Marshal(b, m, deterministic)
}
func (m *ScalarField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarField.Merge(m, src)
}
func (m *ScalarField) XXX_Size() int {
	return xxx_messageInfo_ScalarField.Size(m)
}
func (m *ScalarField) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarField.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarField proto.InternalMessageInfo

type isScalarField_Data interface {
	isScalarField_Data()
}

type ScalarField_BoolData struct {
	BoolData *BoolArray `protobuf:"bytes,1,opt,name=bool_data,json=boolData,proto3,oneof"`
}

type ScalarField_IntData struct {
	IntData *IntArray `protobuf:"bytes,2,opt,name=int_data,json=intData,proto3,oneof"`
}

type ScalarField_LongData struct {
	LongData *LongArray `protobuf:"bytes,3,opt,name=long_data,json=longData,proto3,oneof"`
}

type ScalarField_FloatData struct {
	FloatData *FloatArray `protobuf:"bytes,4,opt,name=float_data,json=floatData,proto3,oneof"`
}

type ScalarField_DoubleData struct {
	DoubleData *DoubleArray `protobuf:"bytes,5,opt,name=double_data,json=doubleData,proto3,oneof"`
}

type ScalarField_StringData struct {
	StringData *StringArray `protobuf:"bytes,6,opt,name=string_data,json=stringData,proto3,oneof"`
}

type ScalarField_BytesData struct {
	BytesData *BytesArray `protobuf:"bytes,7,opt,name=bytes_data,json=bytesData,proto3,oneof"`
}

type ScalarField_ArrayData struct {
	ArrayData *ArrayArray `protobuf:"bytes,8,opt,name=array_data,json=arrayData,proto3,oneof"`
}

type ScalarField_JsonData struct {
	JsonData *JSONArray `protobuf:"bytes,9,opt,name=json_data,json=jsonData,proto3,oneof"`
}

func (*ScalarField_BoolData) isScalarField_Data() {}

func (*ScalarField_IntData) isScalarField_Data() {}

func (*ScalarField_LongData) isScalarField_Data() {}

func (*ScalarField_FloatData) isScalarField_Data() {}

func (*ScalarField_DoubleData) isScalarField_Data() {}

func (*ScalarField_StringData) isScalarField_Data() {}

func (*ScalarField_BytesData) isScalarField_Data() {}

func (*ScalarField_ArrayData) isScalarField_Data() {}

func (*ScalarField_JsonData) isScalarField_Data() {}

func (m *ScalarField) GetData() isScalarField_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ScalarField) GetBoolData() *BoolArray {
	if x, ok := m.GetData().(*ScalarField_BoolData); ok {
		return x.BoolData
	}
	return nil
}

func (m *ScalarField) GetIntData() *IntArray {
	if x, ok := m.GetData().(*ScalarField_IntData); ok {
		return x.IntData
	}
	return nil
}

func (m *ScalarField) GetLongData() *LongArray {
	if x, ok := m.GetData().(*ScalarField_LongData); ok {
		return x.LongData
	}
	return nil
}

func (m *ScalarField) GetFloatData() *FloatArray {
	if x, ok := m.GetData().(*ScalarField_FloatData); ok {
		return x.FloatData
	}
	return nil
}

func (m *ScalarField) GetDoubleData() *DoubleArray {
	if x, ok := m.GetData().(*ScalarField_DoubleData); ok {
		return x.DoubleData
	}
	return nil
}

func (m *ScalarField) GetStringData() *StringArray {
	if x, ok := m.GetData().(*ScalarField_StringData); ok {
		return x.StringData
	}
	return nil
}

func (m *ScalarField) GetBytesData() *BytesArray {
	if x, ok := m.GetData().(*ScalarField_BytesData); ok {
		return x.BytesData
	}
	return nil
}

func (m *ScalarField) GetArrayData() *ArrayArray {
	if x, ok := m.GetData().(*ScalarField_ArrayData); ok {
		return x.ArrayData
	}
	return nil
}

func (m *ScalarField) GetJsonData() *JSONArray {
	if x, ok := m.GetData().(*ScalarField_JsonData); ok {
		return x.JsonData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ScalarField) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ScalarField_BoolData)(nil),
		(*ScalarField_IntData)(nil),
		(*ScalarField_LongData)(nil),
		(*ScalarField_FloatData)(nil),
		(*ScalarField_DoubleData)(nil),
		(*ScalarField_StringData)(nil),
		(*ScalarField_BytesData)(nil),
		(*ScalarField_ArrayData)(nil),
		(*ScalarField_JsonData)(nil),
	}
}

type VectorField struct {
	Dim int64 `protobuf:"varint,1,opt,name=dim,proto3" json:"dim,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*VectorField_FloatVector
	//	*VectorField_BinaryVector
	//	*VectorField_Float16Vector
	//	*VectorField_Bfloat16Vector
	Data                 isVectorField_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VectorField) Reset()         { *m = VectorField{} }
func (m *VectorField) String() string { return proto.CompactTextString(m) }
func (*VectorField) ProtoMessage()    {}
func (*VectorField) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{13}
}

func (m *VectorField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorField.Unmarshal(m, b)
}
func (m *VectorField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorField.Marshal(b, m, deterministic)
}
func (m *VectorField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorField.Merge(m, src)
}
func (m *VectorField) XXX_Size() int {
	return xxx_messageInfo_VectorField.Size(m)
}
func (m *VectorField) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorField.DiscardUnknown(m)
}

var xxx_messageInfo_VectorField proto.InternalMessageInfo

func (m *VectorField) GetDim() int64 {
	if m != nil {
		return m.Dim
	}
	return 0
}

type isVectorField_Data interface {
	isVectorField_Data()
}

type VectorField_FloatVector struct {
	FloatVector *FloatArray `protobuf:"bytes,2,opt,name=float_vector,json=floatVector,proto3,oneof"`
}

type VectorField_BinaryVector struct {
	BinaryVector []byte `protobuf:"bytes,3,opt,name=binary_vector,json=binaryVector,proto3,oneof"`
}

type VectorField_Float16Vector struct {
	Float16Vector []byte `protobuf:"bytes,4,opt,name=float16_vector,json=float16Vector,proto3,oneof"`
}

type VectorField_Bfloat16Vector struct {
	Bfloat16Vector []byte `protobuf:"bytes,5,opt,name=bfloat16_vector,json=bfloat16Vector,proto3,oneof"`
}

func (*VectorField_FloatVector) isVectorField_Data() {}

func (*VectorField_BinaryVector) isVectorField_Data() {}

func (*VectorField_Float16Vector) isVectorField_Data() {}

func (*VectorField_Bfloat16Vector) isVectorField_Data() {}

func (m *VectorField) GetData() isVectorField_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *VectorField) GetFloatVector() *FloatArray {
	if x, ok := m.GetData().(*VectorField_FloatVector); ok {
		return x.FloatVector
	}
	return nil
}

func (m *VectorField) GetBinaryVector() []byte {
	if x, ok := m.GetData().(*VectorField_BinaryVector); ok {
		return x.BinaryVector
	}
	return nil
}

func (m *VectorField) GetFloat16Vector() []byte {
	if x, ok := m.GetData().(*VectorField_Float16Vector); ok {
		return x.Float16Vector
	}
	return nil
}

func (m *VectorField) GetBfloat16Vector() []byte {
	if x, ok := m.GetData().(*VectorField_Bfloat16Vector); ok {
		return x.Bfloat16Vector
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*VectorField) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*VectorField_FloatVector)(nil),
		(*VectorField_BinaryVector)(nil),
		(*VectorField_Float16Vector)(nil),
		(*VectorField_Bfloat16Vector)(nil),
	}
}

type FieldData struct {
	Type      DataType `protobuf:"varint,1,opt,name=type,proto3,enum=milvus.proto.schema.DataType" json:"type,omitempty"`
	FieldName string   `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// Types that are valid to be assigned to Field:
	//	*FieldData_Scalars
	//	*FieldData_Vectors
	Field                isFieldData_Field `protobuf_oneof:"field"`
	FieldId              int64             `protobuf:"varint,5,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	IsDynamic            bool              `protobuf:"varint,6,opt,name=is_dynamic,json=isDynamic,proto3" json:"is_dynamic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FieldData) Reset()         { *m = FieldData{} }
func (m *FieldData) String() string { return proto.CompactTextString(m) }
func (*FieldData) ProtoMessage()    {}
func (*FieldData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{14}
}

func (m *FieldData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldData.Unmarshal(m, b)
}
func (m *FieldData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldData.Marshal(b, m, deterministic)
}
func (m *FieldData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldData.Merge(m, src)
}
func (m *FieldData) XXX_Size() int {
	return xxx_messageInfo_FieldData.Size(m)
}
func (m *FieldData) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldData.DiscardUnknown(m)
}

var xxx_messageInfo_FieldData proto.InternalMessageInfo

func (m *FieldData) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_None
}

func (m *FieldData) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

type isFieldData_Field interface {
	isFieldData_Field()
}

type FieldData_Scalars struct {
	Scalars *ScalarField `protobuf:"bytes,3,opt,name=scalars,proto3,oneof"`
}

type FieldData_Vectors struct {
	Vectors *VectorField `protobuf:"bytes,4,opt,name=vectors,proto3,oneof"`
}

func (*FieldData_Scalars) isFieldData_Field() {}

func (*FieldData_Vectors) isFieldData_Field() {}

func (m *FieldData) GetField() isFieldData_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *FieldData) GetScalars() *ScalarField {
	if x, ok := m.GetField().(*FieldData_Scalars); ok {
		return x.Scalars
	}
	return nil
}

func (m *FieldData) GetVectors() *VectorField {
	if x, ok := m.GetField().(*FieldData_Vectors); ok {
		return x.Vectors
	}
	return nil
}

func (m *FieldData) GetFieldId() int64 {
	if m != nil {
		return m.FieldId
	}
	return 0
}

func (m *FieldData) GetIsDynamic() bool {
	if m != nil {
		return m.IsDynamic
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FieldData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FieldData_Scalars)(nil),
		(*FieldData_Vectors)(nil),
	}
}

type IDs struct {
	// Types that are valid to be assigned to IdField:
	//	*IDs_IntId
	//	*IDs_StrId
	IdField              isIDs_IdField `protobuf_oneof:"id_field"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IDs) Reset()         { *m = IDs{} }
func (m *IDs) String() string { return proto.CompactTextString(m) }
func (*IDs) ProtoMessage()    {}
func (*IDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{15}
}

func (m *IDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDs.Unmarshal(m, b)
}
func (m *IDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDs.Marshal(b, m, deterministic)
}
func (m *IDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDs.Merge(m, src)
}
func (m *IDs) XXX_Size() int {
	return xxx_messageInfo_IDs.Size(m)
}
func (m *IDs) XXX_DiscardUnknown() {
	xxx_messageInfo_IDs.DiscardUnknown(m)
}

var xxx_messageInfo_IDs proto.InternalMessageInfo

type isIDs_IdField interface {
	isIDs_IdField()
}

type IDs_IntId struct {
	IntId *LongArray `protobuf:"bytes,1,opt,name=int_id,json=intId,proto3,oneof"`
}

type IDs_StrId struct {
	StrId *StringArray `protobuf:"bytes,2,opt,name=str_id,json=strId,proto3,oneof"`
}

func (*IDs_IntId) isIDs_IdField() {}

func (*IDs_StrId) isIDs_IdField() {}

func (m *IDs) GetIdField() isIDs_IdField {
	if m != nil {
		return m.IdField
	}
	return nil
}

func (m *IDs) GetIntId() *LongArray {
	if x, ok := m.GetIdField().(*IDs_IntId); ok {
		return x.IntId
	}
	return nil
}

func (m *IDs) GetStrId() *StringArray {
	if x, ok := m.GetIdField().(*IDs_StrId); ok {
		return x.StrId
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IDs) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IDs_IntId)(nil),
		(*IDs_StrId)(nil),
	}
}

type SearchResultData struct {
	NumQueries           int64        `protobuf:"varint,1,opt,name=num_queries,json=numQueries,proto3" json:"num_queries,omitempty"`
	TopK                 int64        `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	FieldsData           []*FieldData `protobuf:"bytes,3,rep,name=fields_data,json=fieldsData,proto3" json:"fields_data,omitempty"`
	Scores               []float32    `protobuf:"fixed32,4,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	Ids                  *IDs         `protobuf:"bytes,5,opt,name=ids,proto3" json:"ids,omitempty"`
	Topks                []int64      `protobuf:"varint,6,rep,packed,name=topks,proto3" json:"topks,omitempty"`
	OutputFields         []string     `protobuf:"bytes,7,rep,name=output_fields,json=outputFields,proto3" json:"output_fields,omitempty"`
	GroupByFieldValue    *FieldData   `protobuf:"bytes,8,opt,name=group_by_field_value,json=groupByFieldValue,proto3" json:"group_by_field_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SearchResultData) Reset()         { *m = SearchResultData{} }
func (m *SearchResultData) String() string { return proto.CompactTextString(m) }
func (*SearchResultData) ProtoMessage()    {}
func (*SearchResultData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{16}
}

func (m *SearchResultData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResultData.Unmarshal(m, b)
}
func (m *SearchResultData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResultData.Marshal(b, m, deterministic)
}
func (m *SearchResultData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResultData.Merge(m, src)
}
func (m *SearchResultData) XXX_Size() int {
	return xxx_messageInfo_SearchResultData.Size(m)
}
func (m *SearchResultData) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResultData.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResultData proto.InternalMessageInfo

func (m *SearchResultData) GetNumQueries() int64 {
	if m != nil {
		return m.NumQueries
	}
	return 0
}

func (m *SearchResultData) GetTopK() int64 {
	if m != nil {
		return m.TopK
	}
	return 0
}

func (m *SearchResultData) GetFieldsData() []*FieldData {
	if m != nil {
		return m.FieldsData
	}
	return nil
}

func (m *SearchResultData) GetScores() []float32 {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *SearchResultData) GetIds() *IDs {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *SearchResultData) GetTopks() []int64 {
	if m != nil {
		return m.Topks
	}
	return nil
}

func (m *SearchResultData) GetOutputFields() []string {
	if m != nil {
		return m.OutputFields
	}
	return nil
}

func (m *SearchResultData) GetGroupByFieldValue() *FieldData {
	if m != nil {
		return m.GroupByFieldValue
	}
	return nil
}

// vector clustering info of data distribution
type VectorClusteringInfo struct {
	// clustering.operationID, id of one clustering operation, a clustering operation contains multiple clusters
	OperationId int64 `protobuf:"varint,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// clustering.centroid
	Centroid *VectorField `protobuf:"bytes,2,opt,name=centroid,proto3" json:"centroid,omitempty"`
	// clustering.size
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// clustering.clusterID, id of one cluster
	ClusterId            int64    `protobuf:"varint,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VectorClusteringInfo) Reset()         { *m = VectorClusteringInfo{} }
func (m *VectorClusteringInfo) String() string { return proto.CompactTextString(m) }
func (*VectorClusteringInfo) ProtoMessage()    {}
func (*VectorClusteringInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{17}
}

func (m *VectorClusteringInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorClusteringInfo.Unmarshal(m, b)
}
func (m *VectorClusteringInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorClusteringInfo.Marshal(b, m, deterministic)
}
func (m *VectorClusteringInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorClusteringInfo.Merge(m, src)
}
func (m *VectorClusteringInfo) XXX_Size() int {
	return xxx_messageInfo_VectorClusteringInfo.Size(m)
}
func (m *VectorClusteringInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorClusteringInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VectorClusteringInfo proto.InternalMessageInfo

func (m *VectorClusteringInfo) GetOperationId() int64 {
	if m != nil {
		return m.OperationId
	}
	return 0
}

func (m *VectorClusteringInfo) GetCentroid() *VectorField {
	if m != nil {
		return m.Centroid
	}
	return nil
}

func (m *VectorClusteringInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *VectorClusteringInfo) GetClusterId() int64 {
	if m != nil {
		return m.ClusterId
	}
	return 0
}

// a clustering operation contains multiple clusters triggered in import or compaction
type VectorClusteringOperation struct {
	// id of a clustering operation
	OperationId int64 `protobuf:"varint,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// clustering parameters such as clustering method, cluster number, etc.
	Params []*commonpb.KeyValuePair `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	// clustering results
	Clusters             []*VectorClusteringInfo `protobuf:"bytes,3,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *VectorClusteringOperation) Reset()         { *m = VectorClusteringOperation{} }
func (m *VectorClusteringOperation) String() string { return proto.CompactTextString(m) }
func (*VectorClusteringOperation) ProtoMessage()    {}
func (*VectorClusteringOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{18}
}

func (m *VectorClusteringOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VectorClusteringOperation.Unmarshal(m, b)
}
func (m *VectorClusteringOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VectorClusteringOperation.Marshal(b, m, deterministic)
}
func (m *VectorClusteringOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VectorClusteringOperation.Merge(m, src)
}
func (m *VectorClusteringOperation) XXX_Size() int {
	return xxx_messageInfo_VectorClusteringOperation.Size(m)
}
func (m *VectorClusteringOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_VectorClusteringOperation.DiscardUnknown(m)
}

var xxx_messageInfo_VectorClusteringOperation proto.InternalMessageInfo

func (m *VectorClusteringOperation) GetOperationId() int64 {
	if m != nil {
		return m.OperationId
	}
	return 0
}

func (m *VectorClusteringOperation) GetParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *VectorClusteringOperation) GetClusters() []*VectorClusteringInfo {
	if m != nil {
		return m.Clusters
	}
	return nil
}

// Scalar field info of data distribution
// todo more definitions
type ScalarClusteringInfo struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScalarClusteringInfo) Reset()         { *m = ScalarClusteringInfo{} }
func (m *ScalarClusteringInfo) String() string { return proto.CompactTextString(m) }
func (*ScalarClusteringInfo) ProtoMessage()    {}
func (*ScalarClusteringInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{19}
}

func (m *ScalarClusteringInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarClusteringInfo.Unmarshal(m, b)
}
func (m *ScalarClusteringInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarClusteringInfo.Marshal(b, m, deterministic)
}
func (m *ScalarClusteringInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarClusteringInfo.Merge(m, src)
}
func (m *ScalarClusteringInfo) XXX_Size() int {
	return xxx_messageInfo_ScalarClusteringInfo.Size(m)
}
func (m *ScalarClusteringInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarClusteringInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarClusteringInfo proto.InternalMessageInfo

func (m *ScalarClusteringInfo) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type DistributionInfo struct {
	VectorClusteringInfos []*VectorClusteringInfo `protobuf:"bytes,1,rep,name=vector_clustering_infos,json=vectorClusteringInfos,proto3" json:"vector_clustering_infos,omitempty"`
	ScalarRangeInfos      []*ScalarClusteringInfo `protobuf:"bytes,2,rep,name=scalar_range_infos,json=scalarRangeInfos,proto3" json:"scalar_range_infos,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                `json:"-"`
	XXX_unrecognized      []byte                  `json:"-"`
	XXX_sizecache         int32                   `json:"-"`
}

func (m *DistributionInfo) Reset()         { *m = DistributionInfo{} }
func (m *DistributionInfo) String() string { return proto.CompactTextString(m) }
func (*DistributionInfo) ProtoMessage()    {}
func (*DistributionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{20}
}

func (m *DistributionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributionInfo.Unmarshal(m, b)
}
func (m *DistributionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributionInfo.Marshal(b, m, deterministic)
}
func (m *DistributionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributionInfo.Merge(m, src)
}
func (m *DistributionInfo) XXX_Size() int {
	return xxx_messageInfo_DistributionInfo.Size(m)
}
func (m *DistributionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DistributionInfo proto.InternalMessageInfo

func (m *DistributionInfo) GetVectorClusteringInfos() []*VectorClusteringInfo {
	if m != nil {
		return m.VectorClusteringInfos
	}
	return nil
}

func (m *DistributionInfo) GetScalarRangeInfos() []*ScalarClusteringInfo {
	if m != nil {
		return m.ScalarRangeInfos
	}
	return nil
}

func init() {
	proto.RegisterEnum("milvus.proto.schema.DataType", DataType_name, DataType_value)
	proto.RegisterEnum("milvus.proto.schema.FieldState", FieldState_name, FieldState_value)
	proto.RegisterType((*FieldSchema)(nil), "milvus.proto.schema.FieldSchema")
	proto.RegisterType((*CollectionSchema)(nil), "milvus.proto.schema.CollectionSchema")
	proto.RegisterType((*BoolArray)(nil), "milvus.proto.schema.BoolArray")
	proto.RegisterType((*IntArray)(nil), "milvus.proto.schema.IntArray")
	proto.RegisterType((*LongArray)(nil), "milvus.proto.schema.LongArray")
	proto.RegisterType((*FloatArray)(nil), "milvus.proto.schema.FloatArray")
	proto.RegisterType((*DoubleArray)(nil), "milvus.proto.schema.DoubleArray")
	proto.RegisterType((*BytesArray)(nil), "milvus.proto.schema.BytesArray")
	proto.RegisterType((*StringArray)(nil), "milvus.proto.schema.StringArray")
	proto.RegisterType((*ArrayArray)(nil), "milvus.proto.schema.ArrayArray")
	proto.RegisterType((*JSONArray)(nil), "milvus.proto.schema.JSONArray")
	proto.RegisterType((*ValueField)(nil), "milvus.proto.schema.ValueField")
	proto.RegisterType((*ScalarField)(nil), "milvus.proto.schema.ScalarField")
	proto.RegisterType((*VectorField)(nil), "milvus.proto.schema.VectorField")
	proto.RegisterType((*FieldData)(nil), "milvus.proto.schema.FieldData")
	proto.RegisterType((*IDs)(nil), "milvus.proto.schema.IDs")
	proto.RegisterType((*SearchResultData)(nil), "milvus.proto.schema.SearchResultData")
	proto.RegisterType((*VectorClusteringInfo)(nil), "milvus.proto.schema.VectorClusteringInfo")
	proto.RegisterType((*VectorClusteringOperation)(nil), "milvus.proto.schema.VectorClusteringOperation")
	proto.RegisterType((*ScalarClusteringInfo)(nil), "milvus.proto.schema.ScalarClusteringInfo")
	proto.RegisterType((*DistributionInfo)(nil), "milvus.proto.schema.DistributionInfo")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 1622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xcd, 0x72, 0xdb, 0xc8,
	0x11, 0x16, 0x08, 0xfe, 0x80, 0x0d, 0x4a, 0x86, 0xc7, 0xb2, 0x4d, 0x3b, 0x25, 0x8b, 0x62, 0x92,
	0x0a, 0xed, 0x8a, 0xa5, 0x58, 0x76, 0x1c, 0xdb, 0x65, 0x57, 0x1c, 0x8a, 0x51, 0xc4, 0x28, 0xb1,
	0x15, 0x28, 0xa5, 0x54, 0xe5, 0x82, 0x02, 0x89, 0x11, 0x35, 0x31, 0x88, 0x41, 0x80, 0x81, 0x2a,
	0xcc, 0x39, 0x79, 0x8b, 0x1c, 0x72, 0xf6, 0x53, 0xec, 0x13, 0x6c, 0xed, 0x71, 0xf7, 0xb2, 0xe7,
	0xdd, 0x27, 0xd8, 0xeb, 0xd6, 0xf4, 0x0c, 0xf8, 0x4f, 0x59, 0xbe, 0xcd, 0xf4, 0x7c, 0xdd, 0x98,
	0xee, 0xfe, 0x7a, 0xba, 0x01, 0xb5, 0xb4, 0x7f, 0x41, 0x87, 0xfe, 0x6e, 0x9c, 0x70, 0xc1, 0xc9,
	0xad, 0x21, 0x0b, 0x2f, 0xb3, 0x54, 0xed, 0x76, 0xd5, 0xd1, 0xfd, 0x5a, 0x9f, 0x0f, 0x87, 0x3c,
	0x52, 0xc2, 0xfb, 0x8d, 0x01, 0xe7, 0x83, 0x90, 0xee, 0xe1, 0xae, 0x97, 0x9d, 0xef, 0x05, 0x34,
	0xed, 0x27, 0x2c, 0x16, 0x3c, 0x51, 0x88, 0xe6, 0xf7, 0x45, 0xb0, 0x0f, 0x19, 0x0d, 0x83, 0x53,
	0xd4, 0x27, 0x75, 0xa8, 0x9c, 0xcb, 0x6d, 0xb7, 0x53, 0x37, 0x1a, 0x46, 0xcb, 0x74, 0xf3, 0x2d,
	0x21, 0x50, 0x8c, 0xfc, 0x21, 0xad, 0x17, 0x1a, 0x46, 0xab, 0xea, 0xe2, 0x9a, 0xfc, 0x0c, 0x36,
	0x58, 0xea, 0xc5, 0x09, 0x1b, 0xfa, 0xc9, 0xc8, 0xfb, 0x40, 0x47, 0x75, 0xb3, 0x61, 0xb4, 0x2c,
	0xb7, 0xc6, 0xd2, 0x13, 0x25, 0x3c, 0xa6, 0x23, 0xd2, 0x00, 0x3b, 0xff, 0x2e, 0xe3, 0x51, 0xbd,
	0x88, 0x06, 0xa6, 0x45, 0xe4, 0x15, 0x54, 0x03, 0x5f, 0xf8, 0x9e, 0x18, 0xc5, 0xb4, 0x5e, 0x6a,
	0x18, 0xad, 0x8d, 0xfd, 0xad, 0xdd, 0x25, 0xee, 0xed, 0x76, 0x7c, 0xe1, 0xff, 0x75, 0x14, 0x53,
	0xd7, 0x0a, 0xf4, 0x8a, 0xb4, 0xc1, 0x96, 0x6a, 0x5e, 0xec, 0x27, 0xfe, 0x30, 0xad, 0x97, 0x1b,
	0x66, 0xcb, 0xde, 0xdf, 0x99, 0xd5, 0xd6, 0x41, 0x39, 0xa6, 0xa3, 0x33, 0x3f, 0xcc, 0xe8, 0x89,
	0xcf, 0x12, 0x17, 0xa4, 0xd6, 0x09, 0x2a, 0x91, 0x0e, 0xd4, 0x58, 0x14, 0xd0, 0x7f, 0xe5, 0x46,
	0x2a, 0xd7, 0x35, 0x62, 0xa3, 0x9a, 0xb6, 0x72, 0x07, 0xca, 0x7e, 0x26, 0x78, 0xb7, 0x53, 0xb7,
	0x30, 0x0a, 0x7a, 0x47, 0x7e, 0x0d, 0xa5, 0x54, 0xf8, 0x82, 0xd6, 0xab, 0xe8, 0xd9, 0xf6, 0x52,
	0xcf, 0x54, 0x12, 0x24, 0xcc, 0x55, 0x68, 0xf2, 0x16, 0x6a, 0x34, 0xa4, 0x43, 0x1a, 0x09, 0x15,
	0x17, 0xb8, 0x4e, 0x5c, 0x6c, 0xad, 0x82, 0xa1, 0xe9, 0xc0, 0x7a, 0x40, 0xcf, 0xfd, 0x2c, 0x14,
	0xde, 0xa5, 0xbc, 0x72, 0xdd, 0x6e, 0x18, 0x2d, 0x7b, 0xc5, 0x05, 0xd0, 0x29, 0xbc, 0x85, 0x5b,
	0xd3, 0x5a, 0x28, 0x22, 0x5b, 0x00, 0x2c, 0xf5, 0x82, 0x51, 0xe4, 0x0f, 0x59, 0xbf, 0x5e, 0x43,
	0xd7, 0xaa, 0x2c, 0xed, 0x28, 0x01, 0x69, 0x81, 0x23, 0x39, 0xe0, 0x27, 0x82, 0xc9, 0x5c, 0x22,
	0x0b, 0xd6, 0x11, 0xb4, 0xc1, 0xd2, 0x93, 0x5c, 0x7c, 0x4c, 0x47, 0xcd, 0xaf, 0x0c, 0x70, 0x0e,
	0x78, 0x18, 0xd2, 0xbe, 0x94, 0x68, 0xc2, 0xe5, 0xb4, 0x32, 0xa6, 0x68, 0x35, 0x47, 0x98, 0xc2,
	0x22, 0x61, 0xee, 0x8f, 0x43, 0x8d, 0x84, 0x6b, 0x17, 0xea, 0xc6, 0x38, 0xdc, 0x2f, 0xa0, 0x8c,
	0x9c, 0x4d, 0xeb, 0x45, 0x4c, 0x63, 0xe3, 0x8a, 0x78, 0xe3, 0xda, 0xd5, 0x78, 0xf2, 0x2b, 0xd8,
	0xa4, 0x91, 0xdf, 0x0b, 0x69, 0xee, 0xad, 0x87, 0x07, 0xc8, 0x48, 0xcb, 0x25, 0xea, 0x4c, 0xfb,
	0x8d, 0xfa, 0xcd, 0x6d, 0xa8, 0xb6, 0x39, 0x0f, 0x7f, 0x97, 0x24, 0xfe, 0x48, 0xba, 0x22, 0x59,
	0x59, 0x37, 0x1a, 0x66, 0xcb, 0x72, 0x71, 0xdd, 0x7c, 0x00, 0x56, 0x37, 0x12, 0x8b, 0xe7, 0x25,
	0x7d, 0xbe, 0x0d, 0xd5, 0x3f, 0xf1, 0x68, 0xb0, 0x08, 0x30, 0x35, 0xa0, 0x01, 0x70, 0x18, 0x72,
	0x7f, 0x89, 0x89, 0x82, 0x46, 0xec, 0x80, 0xdd, 0xe1, 0x59, 0x2f, 0xa4, 0x8b, 0x10, 0x63, 0x62,
	0xa4, 0x3d, 0x12, 0x34, 0x5d, 0x44, 0xd4, 0x26, 0x46, 0x4e, 0x45, 0xc2, 0x96, 0xdd, 0xa4, 0xaa,
	0x21, 0xff, 0x31, 0x00, 0xf0, 0x54, 0x41, 0x9e, 0x4d, 0x41, 0x56, 0x05, 0xf9, 0xb4, 0xef, 0x87,
	0x7e, 0xa2, 0x48, 0x85, 0xe8, 0x05, 0x52, 0x17, 0x3e, 0x97, 0xd4, 0x32, 0x62, 0x7f, 0x3c, 0x7d,
	0xff, 0x6e, 0xb5, 0x2b, 0x3f, 0x18, 0x00, 0x13, 0x32, 0x93, 0x2d, 0xa8, 0xf6, 0x38, 0x0f, 0x3d,
	0x8d, 0x33, 0x5a, 0xd6, 0xd1, 0x9a, 0x6b, 0x49, 0x91, 0xb4, 0x4f, 0x7e, 0x02, 0x16, 0x8b, 0x84,
	0x3a, 0x95, 0x97, 0x29, 0x1d, 0xad, 0xb9, 0x15, 0x16, 0x09, 0x3c, 0xdc, 0x82, 0x6a, 0xc8, 0xa3,
	0x81, 0x3a, 0x95, 0x4c, 0x33, 0xa5, 0xae, 0x14, 0xe1, 0xf1, 0x36, 0xc0, 0xb9, 0xcc, 0x8d, 0x3a,
	0x97, 0xef, 0x5a, 0xe1, 0x68, 0xcd, 0xad, 0xa2, 0x0c, 0x01, 0x3b, 0x60, 0x07, 0x98, 0x1a, 0x85,
	0x90, 0x3c, 0x32, 0x8e, 0xd6, 0x5c, 0x50, 0xc2, 0x1c, 0x92, 0x62, 0xe0, 0x15, 0xa4, 0x2c, 0xb9,
	0x2e, 0x21, 0x4a, 0x98, 0x7f, 0xa6, 0x27, 0xb3, 0xa7, 0x10, 0x95, 0x86, 0xd1, 0xaa, 0xc9, 0xcf,
	0xa0, 0x4c, 0x02, 0xda, 0x65, 0x15, 0x85, 0xe6, 0xb7, 0x45, 0xb0, 0xa7, 0x42, 0x4e, 0xde, 0xcc,
	0xbb, 0x6e, 0xef, 0x3f, 0x58, 0x1a, 0xe9, 0x31, 0x87, 0x67, 0x42, 0xf3, 0x6a, 0x2e, 0x34, 0xf6,
	0x8a, 0x3c, 0xe5, 0x04, 0x9f, 0x8e, 0xdc, 0x9b, 0xf9, 0xc8, 0xad, 0xfa, 0xf4, 0x98, 0xfd, 0x33,
	0x91, 0x7d, 0xbb, 0x10, 0xd9, 0x55, 0xcf, 0xd6, 0xa4, 0x38, 0x66, 0x43, 0x7f, 0xb0, 0x18, 0xfa,
	0x55, 0x2c, 0x9d, 0xaa, 0x9e, 0xb9, 0xe4, 0x1c, 0x2c, 0x26, 0x67, 0x25, 0xd5, 0x27, 0xd5, 0x33,
	0x97, 0xbe, 0xb7, 0x0b, 0xe9, 0x5b, 0xe5, 0xcb, 0xa4, 0x46, 0x67, 0xf2, 0x2b, 0x2d, 0xf8, 0x52,
	0xaa, 0x2c, 0x58, 0x57, 0x58, 0x98, 0xd4, 0xa7, 0xb4, 0x80, 0x4a, 0x79, 0x3a, 0xfe, 0x91, 0xf2,
	0x48, 0x19, 0xa8, 0x5e, 0x91, 0x8e, 0x71, 0x69, 0xc9, 0x74, 0x48, 0x95, 0x19, 0x82, 0x7d, 0x67,
	0x80, 0x7d, 0x46, 0xfb, 0x82, 0x6b, 0x82, 0x39, 0x60, 0x06, 0x6c, 0xa8, 0x27, 0x05, 0xb9, 0x94,
	0x9d, 0x54, 0x25, 0xee, 0x12, 0x61, 0x9a, 0x37, 0xd7, 0x48, 0x9d, 0x8d, 0x6a, 0xca, 0x38, 0xf9,
	0x39, 0xac, 0xf7, 0x58, 0x24, 0x67, 0x0a, 0x6d, 0xc6, 0xd4, 0xa4, 0xaf, 0x29, 0xb1, 0x86, 0xfd,
	0x02, 0x36, 0x50, 0xeb, 0xc9, 0xf3, 0x1c, 0x57, 0xd4, 0xb8, 0x75, 0x2d, 0xd7, 0xc0, 0x87, 0x70,
	0xa3, 0x37, 0x87, 0x2c, 0x69, 0xe4, 0x46, 0x6f, 0x06, 0x3a, 0x76, 0xf5, 0x7f, 0x05, 0xa8, 0xa2,
	0x93, 0x18, 0xbf, 0x27, 0x50, 0xc4, 0xe7, 0xca, 0xb8, 0xce, 0x73, 0x85, 0x50, 0xd9, 0x36, 0xb1,
	0x7b, 0x78, 0x53, 0x53, 0x53, 0x15, 0x25, 0xef, 0x64, 0x8f, 0x7b, 0x0d, 0x95, 0x14, 0x4b, 0x35,
	0xd5, 0xe5, 0xf1, 0xc9, 0x17, 0x54, 0x96, 0x97, 0x56, 0x91, 0xda, 0xca, 0x8f, 0x54, 0x17, 0xc7,
	0x72, 0xed, 0xa9, 0x5c, 0x49, 0x6d, 0xad, 0x42, 0xee, 0x81, 0xa5, 0xae, 0xc6, 0x54, 0x6f, 0x1b,
	0x4f, 0x79, 0xc1, 0x5c, 0xb3, 0x2f, 0xcf, 0x35, 0xfb, 0x76, 0x05, 0x4a, 0x88, 0x6c, 0xfe, 0xd7,
	0x00, 0xb3, 0xdb, 0x49, 0xc9, 0x6f, 0xa0, 0x2c, 0xdf, 0x08, 0x16, 0x5c, 0xf9, 0xbe, 0x4c, 0x17,
	0x79, 0x89, 0x45, 0xa2, 0x1b, 0x90, 0x97, 0x50, 0x4e, 0x45, 0x22, 0x15, 0x0b, 0xd7, 0xae, 0xaa,
	0x52, 0x2a, 0x92, 0x6e, 0xd0, 0x06, 0xb0, 0x58, 0xa0, 0x5a, 0x73, 0xf3, 0x9b, 0x02, 0x38, 0xa7,
	0xd4, 0x4f, 0xfa, 0x17, 0x2e, 0x4d, 0xb3, 0x50, 0xe8, 0x07, 0xd3, 0x8e, 0xb2, 0xa1, 0xf7, 0xcf,
	0x8c, 0x26, 0x8c, 0xa6, 0x9a, 0x9e, 0x10, 0x65, 0xc3, 0xbf, 0x28, 0x09, 0xb9, 0x05, 0x25, 0xc1,
	0x63, 0xef, 0x03, 0x7e, 0xdb, 0x74, 0x8b, 0x82, 0xc7, 0xc7, 0xe4, 0xb7, 0x60, 0xab, 0x39, 0x20,
	0x7f, 0xb4, 0xcc, 0x95, 0xfe, 0x8c, 0x89, 0xe1, 0xaa, 0x1c, 0xab, 0x32, 0xbd, 0x03, 0xe5, 0xb4,
	0xcf, 0x13, 0xaa, 0x06, 0x8f, 0x82, 0xab, 0x77, 0xe4, 0x11, 0x98, 0x2c, 0x48, 0xf5, 0x13, 0x54,
	0x5f, 0xfe, 0x84, 0x76, 0x52, 0x57, 0x82, 0xc8, 0x26, 0xde, 0xec, 0x83, 0x9a, 0x63, 0x4d, 0x57,
	0x6d, 0xc8, 0x4f, 0x61, 0x9d, 0x67, 0x22, 0xce, 0x84, 0xa7, 0x27, 0x9b, 0x0a, 0xf6, 0xe5, 0x9a,
	0x12, 0x1e, 0xaa, 0xe9, 0xe5, 0x3d, 0x6c, 0x0e, 0x12, 0x9e, 0xc5, 0x5e, 0x6f, 0xa4, 0x60, 0x7a,
	0xe8, 0xb3, 0xae, 0x48, 0xcc, 0xc4, 0x91, 0x9b, 0xa8, 0xdb, 0x1e, 0xa1, 0x04, 0xdb, 0x67, 0xf3,
	0xa3, 0x01, 0x9b, 0x8a, 0x41, 0x07, 0x61, 0x96, 0x0a, 0x2a, 0x53, 0xd1, 0x8d, 0xce, 0x39, 0xd9,
	0x81, 0x1a, 0x8f, 0x69, 0xe2, 0xe3, 0xbc, 0xa7, 0x53, 0x6f, 0xba, 0xf6, 0x58, 0xd6, 0x0d, 0xc8,
	0x6b, 0xb0, 0xfa, 0x34, 0x12, 0x09, 0xff, 0x44, 0x82, 0xa7, 0x18, 0xea, 0x8e, 0x35, 0x64, 0x5b,
	0x4f, 0xd9, 0xbf, 0xa9, 0x6a, 0xb9, 0x2e, 0xae, 0x25, 0x33, 0xfb, 0xea, 0x1a, 0xf2, 0x93, 0x45,
	0x3c, 0xa9, 0x6a, 0x49, 0x37, 0x68, 0x7e, 0x61, 0xc0, 0xbd, 0xf9, 0xcb, 0xbe, 0xcf, 0x2f, 0x74,
	0x9d, 0x1b, 0xbf, 0x84, 0xb2, 0x9e, 0xfe, 0x0b, 0xd7, 0x9d, 0xfe, 0xb5, 0x02, 0xf9, 0x3d, 0x58,
	0xfa, 0x22, 0xa9, 0xa6, 0xcd, 0xc3, 0x2b, 0x9c, 0x9d, 0x0d, 0xa6, 0x3b, 0x56, 0x6d, 0xfe, 0x12,
	0x36, 0x55, 0xb9, 0xcf, 0x85, 0x7b, 0x53, 0x17, 0x9d, 0x9e, 0x91, 0x75, 0x05, 0x7e, 0x69, 0x80,
	0xd3, 0x61, 0xb2, 0xcf, 0xf4, 0x32, 0x74, 0x41, 0x42, 0x7d, 0xb8, 0xab, 0x8a, 0xdc, 0xeb, 0x8f,
	0x6d, 0x78, 0x2c, 0x3a, 0xe7, 0xa9, 0x9e, 0xd3, 0x3e, 0xe3, 0x62, 0xb7, 0x2f, 0x97, 0x48, 0x53,
	0xf2, 0x37, 0x20, 0xea, 0x15, 0xf2, 0x12, 0x3f, 0x1a, 0x50, 0x6d, 0xbd, 0x70, 0x85, 0xf5, 0x65,
	0x4e, 0xb9, 0x8e, 0x32, 0xe2, 0x4a, 0x1b, 0x68, 0xf8, 0xd1, 0xd7, 0x06, 0x58, 0xf9, 0x1b, 0x4a,
	0x2c, 0x28, 0xbe, 0xe3, 0x11, 0x75, 0xd6, 0xe4, 0x4a, 0x8e, 0x27, 0x8e, 0x21, 0x57, 0xdd, 0x48,
	0xbc, 0x70, 0x0a, 0xa4, 0x0a, 0xa5, 0x6e, 0x24, 0x9e, 0x3c, 0x77, 0x4c, 0xbd, 0x7c, 0xba, 0xef,
	0x14, 0xf5, 0xf2, 0xf9, 0x33, 0xa7, 0x24, 0x97, 0xd8, 0x5d, 0x1c, 0x20, 0x00, 0x65, 0xd5, 0xe0,
	0x1d, 0x5b, 0xae, 0xd5, 0x8b, 0xe2, 0x6c, 0x12, 0x1b, 0x2a, 0x67, 0x7e, 0x72, 0x70, 0xe1, 0x27,
	0xce, 0x6d, 0x89, 0xc7, 0x47, 0xc6, 0xb9, 0x23, 0xbf, 0x22, 0x9b, 0xa0, 0x73, 0x97, 0x38, 0x50,
	0x6b, 0x4f, 0xb5, 0x1b, 0x27, 0x20, 0x37, 0xc0, 0x3e, 0x9c, 0xb4, 0x29, 0x87, 0x92, 0x9b, 0xb0,
	0x7e, 0x38, 0xdd, 0x3e, 0x9c, 0x73, 0x42, 0x60, 0xa3, 0x3d, 0x2b, 0x1b, 0x3c, 0x3a, 0x03, 0x98,
	0xfc, 0xdf, 0x49, 0xbb, 0xb8, 0x3b, 0x48, 0xa8, 0x2f, 0x68, 0xe0, 0xac, 0xa1, 0x99, 0xb1, 0x44,
	0x5e, 0xcf, 0x18, 0x8b, 0x3a, 0x09, 0x8f, 0x63, 0x29, 0x2a, 0x8c, 0xf5, 0x50, 0x44, 0x03, 0xc7,
	0x6c, 0x0f, 0x61, 0x83, 0xf1, 0x3c, 0xe6, 0x83, 0x24, 0xee, 0xb7, 0x6d, 0xf5, 0x4b, 0x73, 0x22,
	0xe3, 0x7f, 0x62, 0xfc, 0xfd, 0xd9, 0x80, 0x89, 0x8b, 0xac, 0x27, 0xd9, 0xbb, 0xa7, 0x60, 0x8f,
	0x19, 0xcf, 0x57, 0x98, 0xa4, 0xbd, 0x01, 0x7f, 0xec, 0xc7, 0x6c, 0xef, 0x72, 0x7f, 0x4f, 0xa5,
	0x2b, 0xee, 0xfd, 0xdf, 0x30, 0x3e, 0x16, 0xc8, 0x9f, 0x95, 0xd5, 0x83, 0x90, 0xd1, 0x48, 0xec,
	0xfe, 0x21, 0x89, 0xfb, 0xbd, 0x32, 0x6a, 0x3c, 0xfd, 0x31, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x75,
	0xed, 0x33, 0x88, 0x10, 0x00, 0x00,
}
